# Image Version 
FROM node:20-alpine

# Create app directory
RUN mkdir -p /home/app

# Set working directory
WORKDIR /home/app

COPY package*.json /home/app
COPY . /home/app

# Set the environment variable for the API URL
ARG REACT_APP_API_URL
ENV REACT_APP_API_URL $REACT_APP_API_URL

# Install dependencies
RUN npm install

# Expose port 3000
EXPOSE 3000

# Start
CMD [ "npm", "start" ]